### ISSUE TITLE
Remaining Work Error

### ISSUE THREAD

**Issue by Tom4U** [ipatalas/vscode-sprint-planner#40]
I've set up a new user story and added tasks with estimated time.
After publishing, tasks got IDs, but estimated time disappeared.

Now I'm trying to set it again, as shown on your addon documentation, but receive the following error:
`TF401320: Rule Error for field Remaining Work. Error code: InvalidNotEmpty.`

In my file it looks like that:

> US#2 - Name of Story
> Development:
> \- Task 1, 2h [# 3]
> \- Task 2, 1h [# 4]
> \- Task 3, 1h [# 5]

Is it a bug or what am I missing?

PS: Added space to task id only here so no tasks in Github get linked.

**Comment by ipatalas** [comment]
Hmm, did the same and it works just fine:
![image](https://user-images.githubusercontent.com/2623329/196046738-0bb4487d-a8c2-4e77-86b6-9eb91b50650f.png)

Does the same error happens over and over again when you try from scratch? 
Were you able to publish anything successfully before?
What is the process type for your project? You can check this in Project Settings:
![image](https://user-images.githubusercontent.com/2623329/196046948-fdc545a9-aea8-413e-b3de-3aca51ff4e0e.png)
(also did you set that correctly in the settings?)

Try enabling "Debug logging" in extension's settings:
![image](https://user-images.githubusercontent.com/2623329/196047064-2a500406-7b74-48ca-b40b-580f3dcb4999.png)
After that turn on Developer Tools and try doing the same operation again.
![image](https://user-images.githubusercontent.com/2623329/196047155-bb3e770e-08bd-4278-a17d-f241cde5a56a.png)

If we're lucky you should get some more info about this `TF401320` error which you got from Azure DevOps API.

Alternatively you can check output log of the extension here:
![image](https://user-images.githubusercontent.com/2623329/196047304-54154bed-2be8-4119-8c8f-72909557d2fc.png)

If there is anything useful there please copy that here (redact anything personal if needed)

**Comment by ipatalas** [comment]
One more thing to check came to my mind.
When you will be checking the process in project settings it's actually a link. 
Try clicking it, if you have permissions you should be able to see a list of all different types of objects:
![image](https://user-images.githubusercontent.com/2623329/196047852-ba950c2e-40af-48fe-8f86-547fdf315cdf.png)

Click Task (I believe it failed there) and see what is the type for Remaining and Original Estimate:
![image](https://user-images.githubusercontent.com/2623329/196047888-0c527506-8ffb-4969-97ba-8950a6888f28.png)
By default it's decimal but maybe you have custom settings and that's why it fails.

**Comment by Tom4U** [comment]
Never mind. I've noticed this happens to closed tasks only. Works as expected, I guess.
